travis:
  secure:
    BINSTAR_TOKEN: k7FROtsybwf9+Prj2uQYHCI1XG6iZPG1wmQ1glP3+kF1FTICU1/9ILZ6FBvHOgkJqnh3iAzSjyIO9KKNnfquHqxbtNz19NFKYIgs1qKnn9m5/+/lfPch05wEV1hu/+Sq1t5+LJxYPKzwRqTUzti8mCwD8UDJJI6qChena9tr8HuoRM4BusC7oQPmnRK9iJSMZgFgZJTHpPHdPwZh0Q1fYupg+qQuPrcQFRUU5w5uQDxAFDDpSCi6cNxcRALO47jRO0kPtZ92BHXCbHNRpg3HJuK1bPZasLeofbQCbo8YG6ZIPhUBjB50xAALptRXYx1nLalW5qaZMEiJ9bfPd5nVG8HMPvi9KpTLxdk0GByrZ/z37LAWDmoOxaj+VrOAos5bnUdDN8VZB7DhnchNo9M4JQ/oSbL2W4YZnnIBmj/67MbGTNX6lnxtJKRZfVBW44Rz/H1Yojr9aQIAHu74AIa0LZXgi7bETawWV+UsQ3RpqlXBXIhV+4wvm8x5W26FE73pFSZh6xApPY/zY2tLLDFKKOLnx2ECw0rO6iS04ctPFbu6UMoDhkUZ8jvxBq5taf/ieNnzZmKJmj/oTUS+0f76QkEq1jFrH/dEUb5/XlpCMwphsdjP96MKDmptD356FJF3U72fA4gKLo8OrPxjMNk6eQ2t7fNKEk88bOz5kmlgETI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
